version: '3.9'

services:
  frontend:
    build: 
      context: ../aia_test_frontend/
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      - REACT_APP_API_URL=${BASE_URL}:${APP_PORT}
    ports:
      - 80:3000
    depends_on:
      - backend
      
  backend:
    build: 
      context: ../aia_test_backend/
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - APP_PORT=${APP_PORT}
    ports:
      - ${BASE_URL}:${APP_PORT}:${APP_PORT}
    
